/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ad05_naranjo_antonio;

import java.io.IOException;
import javax.swing.JOptionPane;
import org.basex.core.BaseXException;

/**
 *
 * @author anaranjo
 */
public class InterfazGrafica extends javax.swing.JFrame {

    // Atributo para el manejador de base de datos XML
    private ManejadorXML manejador;

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
        // Se ajusta el tamaño de la ventana al contenido
        this.pack();
        // Se centra la ventana en la pantalla (después de pack)
        this.setLocationRelativeTo(null);
        // Se anula inicialmente el botón generar ficheros hasta que la base de datos no esté operativa
        jButtonGenerarFicheros.setEnabled(false);
        jButtonListarProveedores.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomBD = new javax.swing.JTextField();
        jTextFieldDirectorioBDxml = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEnt3 = new javax.swing.JTextField();
        jTextFieldEnt2 = new javax.swing.JTextField();
        jTextFieldEnt1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldxPath1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldxPath2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldxPath3 = new javax.swing.JTextField();
        jPanelEntidad = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButtonListarProveedores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaListadoProveedores = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButtonGenerarFicheros = new javax.swing.JButton();
        jButtonInicarBD = new javax.swing.JButton();
        jPanelXpath = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base de datos XML TechSolutions | AD Tarea 05 - Antonio Naranjo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Ejercicio 1 >> Generar ficheros");
        jLabel1.setToolTipText("Generar ficheros de las siguiente entidades");

        jTextFieldNomBD.setText("Colecciones2526");
        jTextFieldNomBD.setToolTipText("Nombre del directorio donde se guardarán los ficheros de las entidades (en la carpeta raíz del proyecto)");
        jTextFieldNomBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomBDActionPerformed(evt);
            }
        });

        jTextFieldDirectorioBDxml.setText("src/recursos/empresaTechSolutions.xml");
        jTextFieldDirectorioBDxml.setToolTipText("Ruta relativa de acceso a la base de datos XML");
        jTextFieldDirectorioBDxml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirectorioBDxmlActionPerformed(evt);
            }
        });

        jLabel5.setText("Directorio: ");

        jLabel6.setText("Ruta BD XML: ");

        jLabel7.setText("Nombre base de datos: ");

        jTextFieldDir.setText("Colecciones2526");
        jTextFieldDir.setToolTipText("Nombre del directorio donde se guardarán los ficheros de las entidades (en la carpeta raíz del proyecto)");
        jTextFieldDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirActionPerformed(evt);
            }
        });

        jLabel2.setText("Entidad 1: ");

        jLabel3.setText("Entidad 2: ");

        jLabel4.setText("Entidad 3: ");

        jTextFieldEnt3.setText("proveedor");
        jTextFieldEnt3.setToolTipText("Nombre de la entidad 3");
        jTextFieldEnt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnt3ActionPerformed(evt);
            }
        });

        jTextFieldEnt2.setText("cliente");
        jTextFieldEnt2.setToolTipText("Nombre de la entidad 2");
        jTextFieldEnt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnt2ActionPerformed(evt);
            }
        });

        jTextFieldEnt1.setText("empleado");
        jTextFieldEnt1.setToolTipText("Nombre de la entidad 1");
        jTextFieldEnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnt1ActionPerformed(evt);
            }
        });

        jLabel8.setText("xPath entidad 1:");

        jTextFieldxPath1.setText("//empleados/empleado");
        jTextFieldxPath1.setToolTipText("Consulta xPath de la entidad 1");
        jTextFieldxPath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldxPath1ActionPerformed(evt);
            }
        });

        jLabel9.setText("xPath entidad 2:");

        jTextFieldxPath2.setText("//clientes/cliente");
        jTextFieldxPath2.setToolTipText("Consulta xPath de la entidad 2");
        jTextFieldxPath2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldxPath2ActionPerformed(evt);
            }
        });

        jLabel10.setText("xPath entidad 3:");

        jTextFieldxPath3.setText("//proveedores/proveedor");
        jTextFieldxPath3.setToolTipText("Consulta xPath de la entidad 3");
        jTextFieldxPath3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldxPath3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldEnt1)
                                    .addComponent(jTextFieldEnt2)
                                    .addComponent(jTextFieldEnt3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDir)
                                    .addComponent(jTextFieldNomBD))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(jTextFieldDirectorioBDxml))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldxPath1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldxPath2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldxPath3)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNomBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDirectorioBDxml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldEnt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldEnt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldEnt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldxPath1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldxPath2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldxPath3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Ejercicio 2.a >> Listar todos los proveedores");
        jLabel11.setToolTipText("Listar todos los proveedores");

        jButtonListarProveedores.setText("Listar proveedores");
        jButtonListarProveedores.setToolTipText("Haz clic para crear los ficheros de las entidades en el directorio definido");
        jButtonListarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarProveedoresActionPerformed(evt);
            }
        });

        jTextAreaListadoProveedores.setColumns(20);
        jTextAreaListadoProveedores.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextAreaListadoProveedores.setRows(5);
        jScrollPane1.setViewportView(jTextAreaListadoProveedores);

        javax.swing.GroupLayout jPanelEntidadLayout = new javax.swing.GroupLayout(jPanelEntidad);
        jPanelEntidad.setLayout(jPanelEntidadLayout);
        jPanelEntidadLayout.setHorizontalGroup(
            jPanelEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEntidadLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelEntidadLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListarProveedores)))
                .addContainerGap())
        );
        jPanelEntidadLayout.setVerticalGroup(
            jPanelEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntidadLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanelEntidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListarProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jButtonGenerarFicheros.setText("Generar ficheros de entidades");
        jButtonGenerarFicheros.setToolTipText("Haz clic para crear los ficheros de las entidades en el directorio definido");
        jButtonGenerarFicheros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarFicherosActionPerformed(evt);
            }
        });

        jButtonInicarBD.setText("Iniciar base de datos XML");
        jButtonInicarBD.setToolTipText("Haz clic para crear los ficheros de las entidades en el directorio definido");
        jButtonInicarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicarBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInicarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonGenerarFicheros)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerarFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInicarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelXpathLayout = new javax.swing.GroupLayout(jPanelXpath);
        jPanelXpath.setLayout(jPanelXpathLayout);
        jPanelXpathLayout.setHorizontalGroup(
            jPanelXpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        jPanelXpathLayout.setVerticalGroup(
            jPanelXpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jButtonSalir.setText("Salir de la aplicación");
        jButtonSalir.setToolTipText("Haz clic para crear los ficheros de las entidades en el directorio definido");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelXpath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelXpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDirActionPerformed

    private void jButtonGenerarFicherosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarFicherosActionPerformed
        // TODO add your handling code here:

        // Comprobamos el estado del manejador antes de nada
        if (manejador != null) {
            try {
                // 1. Recogemos el directorio y validamos que no esté vacío
                String directorioStr = jTextFieldDir.getText().trim();
                
                if (directorioStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe especificar un nombre para el directorio de destino.");
                } else {
                    // 2. Preparamos los arrays con la información de los JTextFields
                    String[] entidades = {jTextFieldEnt1.getText(), jTextFieldEnt2.getText(), jTextFieldEnt3.getText()};
                    String[] xpaths = {jTextFieldxPath1.getText(), jTextFieldxPath2.getText(), jTextFieldxPath3.getText()};

                    // 3. Llamamos al método masivo del manejador
                    manejador.exportarDesdeInterfaz(directorioStr, entidades, xpaths);

                    // 4. Éxito: Feedback visual para el usuario
                    JOptionPane.showMessageDialog(this, "Proceso finalizado correctamente.\nFicheros generados en: " + directorioStr);
                }
                
            } catch (BaseXException ex) {
                // Si el error viene específicamente de BaseX (ej: error en XPath)
                JOptionPane.showMessageDialog(this, "Error de BaseX: " + ex.getMessage(), "Error en Motor XML", JOptionPane.ERROR_MESSAGE);
                
            } catch (IOException e) {
                // Errores de disco, permisos, carpeta...
                JOptionPane.showMessageDialog(this, "Error de archivos: " + e.getMessage(), "Error E/S", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                // Errores de BaseX, consultas XPath mal escritas, etc.
                JOptionPane.showMessageDialog(this, "Error en Base de Datos: " + e.getMessage(), "Error XML", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Este caso técnicamente no debería ocurrir si el botón está desactivado, 
            // pero lo mantenemos como red de seguridad profesional.
            JOptionPane.showMessageDialog(this, "La base de datos no está iniciada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonGenerarFicherosActionPerformed

    private void jTextFieldDirectorioBDxmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirectorioBDxmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDirectorioBDxmlActionPerformed

    private void jTextFieldEnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnt1ActionPerformed

    private void jTextFieldEnt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnt2ActionPerformed

    private void jTextFieldEnt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnt3ActionPerformed

    private void jTextFieldNomBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomBDActionPerformed

    private void jTextFieldxPath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldxPath1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldxPath1ActionPerformed

    private void jTextFieldxPath2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldxPath2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldxPath2ActionPerformed

    private void jTextFieldxPath3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldxPath3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldxPath3ActionPerformed

    private void jButtonInicarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicarBDActionPerformed
        // TODO add your handling code here:

        try {
            // Obtenemos los datos de la interfaz
            String nombre = jTextFieldNomBD.getText().trim();
            String ruta = jTextFieldDirectorioBDxml.getText().trim();

            // Validación básica de campos vacíos
            if (nombre.isEmpty() || ruta.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, rellene el nombre y la ruta del XML.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            } else {
                // Instanciamos el manejador (esto ejecuta el conectar() interno)
                manejador = new ManejadorXML(nombre, ruta);
                
                JOptionPane.showMessageDialog(this, "Conexión con BaseX establecida con éxito.");

                // Si todo ha ido bien, habilitamos el botón de generar
                jButtonInicarBD.setEnabled(false);
                jButtonGenerarFicheros.setEnabled(true);
                jButtonListarProveedores.setEnabled(true);
                jTextFieldNomBD.setEditable(false);
                jTextFieldDirectorioBDxml.setEditable(false);
            }
        } catch (Exception e) {
            // Si el XML no existe o BaseX falla, capturamos el error aquí
            JOptionPane.showMessageDialog(this, "Error al iniciar base de datos: " + e.getMessage(), "Error de Conexión", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonInicarBDActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas salir?", "Confirmar salida",
                JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            if (manejador != null) {
                manejador.cerrar();
            }
            System.exit(0); // Cerramos todo
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas salir?", "Confirmar salida",
                JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            if (manejador != null) {
                manejador.cerrar();
            }
            System.exit(0); // Cerramos todo
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButtonListarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarProveedoresActionPerformed
        // TODO add your handling code here:
        if (manejador != null) {
            try {
                String listado = manejador.obtenerListadoProveedores();
                jTextAreaListadoProveedores.setText(listado);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al listar proveedores: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonListarProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarFicheros;
    private javax.swing.JButton jButtonInicarBD;
    private javax.swing.JButton jButtonListarProveedores;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelEntidad;
    private javax.swing.JPanel jPanelXpath;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaListadoProveedores;
    private javax.swing.JTextField jTextFieldDir;
    private javax.swing.JTextField jTextFieldDirectorioBDxml;
    private javax.swing.JTextField jTextFieldEnt1;
    private javax.swing.JTextField jTextFieldEnt2;
    private javax.swing.JTextField jTextFieldEnt3;
    private javax.swing.JTextField jTextFieldNomBD;
    private javax.swing.JTextField jTextFieldxPath1;
    private javax.swing.JTextField jTextFieldxPath2;
    private javax.swing.JTextField jTextFieldxPath3;
    // End of variables declaration//GEN-END:variables
}
